### ISSUE TITLE
AttributeError: module 'comtypes.gen.UIAutomationClient' has no attribute 'CUIAutomation

### ISSUE THREAD

**Issue by Stephano120** [pywinauto/pywinauto#961]
## Expected Behavior
When running a script with a very single line such as 
`from pywinauto import Application`
or
`import pywinauto`, 
I should not get any error message.

## Actual Behavior
I do get error messages:
`D:\PycharmProjects\project_a\venv\lib\site-packages\pywinauto\__init__.py:72: UserWarning: Apply externally defined coinit_flags: 0
  .format(module_sys.coinit_flags), UserWarning)
Traceback (most recent call last):
  File "<input>", line 1, in <module>
  File "C:\Program Files (x86)\JetBrains\PyCharm Community Edition 2018.1\helpers\pydev\_pydev_bundle\pydev_import_hook.py", line 20, in do_import
    module = self._system_import(name, *args, **kwargs)
  File "D:\PycharmProjects\project_a\venv\lib\site-packages\pywinauto\__init__.py", line 89, in <module>
    from . import findwindows
  File "C:\Program Files (x86)\JetBrains\PyCharm Community Edition 2018.1\helpers\pydev\_pydev_bundle\pydev_import_hook.py", line 20, in do_import
    module = self._system_import(name, *args, **kwargs)
  File "D:\PycharmProjects\project_a\venv\lib\site-packages\pywinauto\findwindows.py", line 42, in <module>
    from . import controls
  File "C:\Program Files (x86)\JetBrains\PyCharm Community Edition 2018.1\helpers\pydev\_pydev_bundle\pydev_import_hook.py", line 20, in do_import
    module = self._system_import(name, *args, **kwargs)
  File "D:\PycharmProjects\project_a\venv\lib\site-packages\pywinauto\controls\__init__.py", line 36, in <module>
    from . import uiawrapper # register "uia" back-end (at the end of uiawrapper module)
  File "C:\Program Files (x86)\JetBrains\PyCharm Community Edition 2018.1\helpers\pydev\_pydev_bundle\pydev_import_hook.py", line 20, in do_import
    module = self._system_import(name, *args, **kwargs)
  File "D:\PycharmProjects\project_a\venv\lib\site-packages\pywinauto\controls\uiawrapper.py", line 47, in <module>
    from ..uia_defines import IUIA
  File "C:\Program Files (x86)\JetBrains\PyCharm Community Edition 2018.1\helpers\pydev\_pydev_bundle\pydev_import_hook.py", line 20, in do_import
    module = self._system_import(name, *args, **kwargs)
  File "D:\PycharmProjects\project_a\venv\lib\site-packages\pywinauto\uia_defines.py", line 181, in <module>
    pattern_ids = _build_pattern_ids_dic()
  File "D:\PycharmProjects\project_a\venv\lib\site-packages\pywinauto\uia_defines.py", line 169, in _build_pattern_ids_dic
    if hasattr(IUIA().ui_automation_client, cls_name):
  File "D:\PycharmProjects\project_a\venv\lib\site-packages\pywinauto\uia_defines.py", line 50, in __call__
    cls._instances[cls] = super(_Singleton, cls).__call__(*args, **kwargs)
  File "D:\PycharmProjects\project_a\venv\lib\site-packages\pywinauto\uia_defines.py", line 63, in __init__
    self.ui_automation_client.CUIAutomation().IPersist_GetClassID(),
**AttributeError: module 'comtypes.gen.UIAutomationClient' has no attribute 'CUIAutomation**'`

I found kind of similar issue described there:
https://github.com/pywinauto/pywinauto/issues/513

But reinstalling comtypes==1.1.5 didnt change anything. Currently, I do have comtypes==1.1.7 installed.
To be accurate, when I forced the installation of comtypes==1.1.5, it failed, and rolled back to 1.1.7.

pywinauto was installed without any issue.

In my venv there is also:
pywin32==228
pywinauto==0.6.8
win32core==221.36
win32gui==221.6

## Steps to Reproduce the Problem

  1.
  2.
  3.

## Short Example of Code to Demonstrate the Problem
pip install pywinauto, #no issue
from pywinauto import Application # it fails
import pywinauto # it fails as well.

## Specifications

  - Pywinauto version: 0.6.8
  - Python version and bitness: Python 3.6
  - Platform and OS: Windows 7

I'm clueless regarding the cause of this issue.

**Comment by eshraj302** [comment]
I was having the same problem when using Python 3.8.5, just changed the python version to 3.8.3, that solved the problem for me!, Try this out and let me know

**Comment by Stephano120** [comment]
Mmmh ok I wil try this, thanks for the hint!
Will let you know if it fixes the issue

**Comment by eshraj302** [comment]
Please close this issue, if the problem has resolved.

**Comment by vasily-v-ryabov** [comment]
Hi @eshraj302 thanks for more details on problem reproduction. If it is Python 3.8.5 specific, it should be investigated anyway to figure out if it's Python bug or some update in Python that could be adopted in comtypes. I'd prefer to keep the issue open so far.

**Comment by Stephano120** [comment]
@vasily-v-ryabov and eshraj302, so far I've tested on Python 3.6 only. I will test with 3.8.3 in a few days. No access to my machine right now.

**Comment by eshraj302** [comment]
Okay sure, Let us know about any Update :)

**Comment by manju1847** [comment]
I am seeing the same issue with Python 3.7.4.

Here are the other details:
Installed comtypes-1.1.12, six-1.16.0 and pywinauto-0.6.8

Please someone help me how to resolve this

![image](https://user-images.githubusercontent.com/101901889/161653082-a676f53d-1631-4507-acd3-09fd60688864.png)

**Comment by manju1847** [comment]
Upgraded my environment still the same issue. 

Here are the details of my upgraded environment 
Python version 3.8.3
PyWin32 version 303
comtypes version 1.1.12
Six version version 1.16.0
PyWinAuto version 0.6.8

![image](https://user-images.githubusercontent.com/101901889/161655905-75e15908-c817-4e8d-b61d-6172f0f3ff55.png)
![image](https://user-images.githubusercontent.com/101901889/161655937-4a47b09d-38bf-4a51-b9d0-1969ff140e16.png)

**Comment by manju1847** [comment]
Its working with comtypes 1.1.11. Please see the below screen shot

![image](https://user-images.githubusercontent.com/101901889/161868009-a7105bad-1890-40e0-9cb2-ad46eef62f79.png)

**Comment by x1nas** [comment]
Есть две виртуалки с pywinauto.
Состав и версии python пакетов идентичны.
Python 3.8.10.
В одном случае возникает ошибка
```
AttributeError: module 'comtypes.gen.UIAutomationClient' has no attribute 'CUIAutomation'
```
В другом - такой ошибки не возникает и все работает.

В тикетах никакого решения не нашел.

**Comment by x1nas** [comment]
> Есть две виртуалки с pywinauto. Состав и версии python пакетов идентичны. Python 3.8.10. В одном случае возникает ошибка
> 
> ```
> AttributeError: module 'comtypes.gen.UIAutomationClient' has no attribute 'CUIAutomation'
> ```
> 
> В другом - такой ошибки не возникает и все работает.
> 
> В тикетах никакого решения не нашел.

Прощу прощения - просмотрел команду по очистке кэша https://github.com/pywinauto/pywinauto/issues/513#issuecomment-411556088 .

В моем случае команда выглядела следующим образом (Powershell от Администратора):
```
& 'C:\Program Files\Python38\python.exe' 'C:\Program Files\Python38\Scripts\clear_comtypes_cache.py' -y
```

После выполнения команды - проблема перестала возникать.
Перезагрузка не требуется, достаточно перезапустить Python.
