### ISSUE TITLE
Windows 11 Breaking changes (as expected)

### ISSUE THREAD

**Issue by 07pepa** [pywinauto/pywinauto#1125]
## Expected Behavior
Since there is no compatibility list in wiki (or i missed it) this should work

## Actual Behavior
crash (not enought rights to acces file in site-packages/comtypes/gen  (i think it is a wright priveledge) 

and once i resolved it  it crashes again on  
`module 'comtypes.gen.UIAutomationClient' has no attribute 'CUIAutomation'` (full traceback at end)

## Steps to Reproduce the Problem
  1. migrate windows 10 to 11
  2. run script that used to work
  3. fix premissions
  4. clean install off Python 3.9.7 does not help

## Specifications
  - Pywinauto version: 0.6.8
  - Python version and bitness: Python 3.9.7
  - Platform and OS: windows 11 x64 (build 22000.194)

## Traceback
  ```
  File "<Redacted but hapen durring import>", line 14, in <module>
    from pywinauto import Application
  File "C:\Program Files\Python39\lib\site-packages\pywinauto\__init__.py", line 89, in <module>
    from . import findwindows
  File "C:\Program Files\Python39\lib\site-packages\pywinauto\findwindows.py", line 42, in <module>
    from . import controls
  File "C:\Program Files\Python39\lib\site-packages\pywinauto\controls\__init__.py", line 36, in <module>
    from . import uiawrapper # register "uia" back-end (at the end of uiawrapper module)
  File "C:\Program Files\Python39\lib\site-packages\pywinauto\controls\uiawrapper.py", line 47, in <module>
    from ..uia_defines import IUIA
  File "C:\Program Files\Python39\lib\site-packages\pywinauto\uia_defines.py", line 181, in <module>
    pattern_ids = _build_pattern_ids_dic()
  File "C:\Program Files\Python39\lib\site-packages\pywinauto\uia_defines.py", line 169, in _build_pattern_ids_dic
    if hasattr(IUIA().ui_automation_client, cls_name):
  File "C:\Program Files\Python39\lib\site-packages\pywinauto\uia_defines.py", line 50, in __call__
    cls._instances[cls] = super(_Singleton, cls).__call__(*args, **kwargs)
  File "C:\Program Files\Python39\lib\site-packages\pywinauto\uia_defines.py", line 63, in __init__
    self.ui_automation_client.CUIAutomation().IPersist_GetClassID(),
AttributeError: module 'comtypes.gen.UIAutomationClient' has no attribute 'CUIAutomation'```

**Comment by 07pepa** [comment]
it may be bad luck after migrating back to 10 a full uninstall (with manual removal of pip files from app data) was needed to be done to make it work again... but before i migrated back  a forced reinstal via pip was also attempted. 

also bitnes was x64

**Comment by vasily-v-ryabov** [comment]
Well, such issues happen when `comtypes` cache is broken. So removing and installing `comtypes` from scratch should help. If you meet this issue again and `comtypes` cache clean up doesn't help, please re-open it.
